<?php

define("ROOT", __DIR__.DIRECTORY_SEPARATOR);
define("VIEW", ROOT."app".DIRECTORY_SEPARATOR."view".DIRECTORY_SEPARATOR);
define("CONTROLLER", ROOT."app".DIRECTORY_SEPARATOR."controller".DIRECTORY_SEPARATOR);
define("CORE", ROOT."app".DIRECTORY_SEPARATOR."core".DIRECTORY_SEPARATOR);
define("MODEL", ROOT."app".DIRECTORY_SEPARATOR."model".DIRECTORY_SEPARATOR);

require_once(CORE. "application.php");

new Application();